# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Workshop Description
    url: '#description'
    weight: 10
  - name: Quran QA Shared Task
    url: '#shared-task'
    weight: 20
  - name: Topics of Interest
    url: '#topics'
    weight: 30
  - name: Important Dates
    url: '#dates'
    weight: 40
  - name: Submission
    url: '#submission'
    weight: 50 
  - name: Committees
    url: '#committees'
    weight: 60
  - name: Previous OSACT Proceedings
    url: '#proceedings'
    weight: 70  
  - name: Fine-grained detection of hate speech on Arabic Twitter Shared Task
    url: '#shared-task2'
    weight: 35

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/uploads/resume.pdf` and uncomment the lines below.
#  - name: CV
#    url: uploads/resume.pdf
#    weight: 70
